version: '3.8'

services:
  web:
    build: .
    container_name: relay-web
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  cron:
    build: .
    container_name: relay-cron
    # Устанавливаем cron и запускаем его в фоновом режиме
    command: >
      bash -c "apt-get update && apt-get install -y cron &&
               python manage.py crontab add &&
               cron -f"
