services:
  web:
    build: .
    container_name: relay-web
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  cron:
    build: .
    container_name: relay-cron
    command: >
      bash -c "python manage.py crontab add && cron -f"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
