# Generated by Django 6.0.7 on 2026-07-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('description', models.CharField(max_length=200, verbose_name='Описание платы')),
                ('is_available', models.BooleanField(default=False, verbose_name='Доступна')),
                ('relay1_description', models.CharField(blank=True, max_length=200, verbose_name='Описание реле 1')),
                ('relay2_description', models.CharField(blank=True, max_length=200, verbose_name='Описание реле 2')),
                ('relay1_state', models.BooleanField(blank=True, default=None, null=True, verbose_name='Состояние реле 1')),
                ('relay2_state', models.BooleanField(blank=True, default=None, null=True, verbose_name='Состояние реле 2')),
            ],
            options={
                'verbose_name': 'Плата',
                'verbose_name_plural': 'Платы',
            },
        ),
    ]
