# Generated by Django 6.0.7 on 2026-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_schedulesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesettings',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False, verbose_name='Автосинхронизация каждые 10 мин'),
        ),
    ]
